### ISSUE TITLE
PRACTICA 6

### ISSUE THREAD

**Issue by ArcangelGC** [SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-con-web-30-mejorado-equipowar#1]
[PRACTICA 6 F .pdf](https://github.com/user-attachments/files/17156880/PRACTICA.6.F.pdf)

**Comment by HECTOR-KDM02** [comment]
20 puntos 

Todo entregado de manera correcta y sin detalles

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
